config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admins, :controllers => {
    :sessions => 'admins/sessions'
  }
  
  devise_scope :admin do
    get "dashboard", :to => 'dashboard#index'
    get "dashboard/login", :to => "admins/sessions#new"
    post "dashboard/login", :to => "admins/sessions#create"
    delete "dashboard/logout", :to => "admins/sessions#destroy"
  end
  
  namespace :dashboard do
    resources :users, only: [:index, :destroy]
    resources :major_categories, except: [:new]
    resources :categories, except: [:new]
    resources :products, except: [:show] do
      collection do
        get  "import/csv", :to => "products#import"
        post "import/csv", :to => "products#import_csv"
        get  "import/csv_download", :to => "products#download_csv"
      end
    end
    resources :orders, only: [:index]
  end
  
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords',
    :confirmations => 'users/confirmations',
    :unlocks => 'users/unlocks',
  }
  
  devise_scope :user do
    root :to => "web#index"
    get "signup", :to => "users/registrations#new"
    get "verify", :to => "users/registrations#verify"
    get "login", :to => "users/sessions#new"
    delete "logout", :to => "users/sessions#destroy"
  end
  
  resource :users, only: [:edit, :update] do
    collection do
      get "cart", :to => "shopping_carts#index"
      post "cart/create", :to => "shopping_carts#create"
      delete "cart", :to => "shopping_carts#destroy"
      get 'mypage', :to => "users#mypage"
      get 'mypage/edit', :to => "users#edit"
      get 'mypage/address/edit', :to => "users#edit_address" 
      get "mypage", :to => "users#update"
      get "mypage/edit_password", :to => "users#edit_password"
      put "mypage/password", :to => "users#update_password"
      get  "mypage/favorite", :to => "users#favorite"
      delete "mypage/delete", :to => "users#destroy"
      get "mypage/cart_history", :to => "users#cart_history_index", :as => "mypage_cart_histories"
      get "mypage/cart_history/:num", :to => "users#cart_history_show", :as => "mypage_cart_history"
      get    "mypage/register_card",     :to => "users#register_card"
      post   "mypage/token",             :to => "users#token"
    end
  end
  
  resources :products do
    member  do
      get :favorite
    end
    resources :reviews, only: [:create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :reviews
  has_one_attached :image
  
  def reviews_new
      reviews.new
  end
  
  def reviews_with_id
    reviews.reviews_with_id
  end
  
  
  extend DisplayList
  scope :on_category, -> (category) { where(category_id: category) }
  
  scope :sort_order, -> (order) { order(order) }
  scope :category_products, -> (category, page) { 
    on_category(category).
    display_list(page)
  }
  
  scope :search_for_id_and_name, -> (keyword) {
    where("name LIKE ?", "%#{keyword}%").or(where("id LIKE ?", "%#{keyword}%"))
  }
  
  scope :sort_products, -> (sort_order, page) {
    on_category(sort_order[:sort_category]).
    sort_order(sort_order[:sort]).
    display_list(page)
  }
  
  scope :sort_list, -> {
    {
      "並び替え" => "",
      "価格の安い順" => "price asc",
      "価格の高い順" => "price desc",
      "出品の古い順" => "updated_at asc", 
      "出品の新しい順" => "updated_at desc",
    }
  }
  
  scope :recently_products, -> (number) { order(created_at: "desc").take(number) }
  scope :recommend_products, -> (number) { where(recommended_flag: true).take(number) }
  scope :check_products_carriage_list, -> (product_ids) { where(id: product_ids).pluck(:carriage_flag)}
  
  def self.import_csv(file)
    new_products = []
    update_products = []
    
    CSV.foreach(file.path, headers: true, encoding: "Shift_JIS:UTF-8") do |row|
      row_to_hash = row.to_hash
      byebug
      if row_to_hash[:id].present?
        update_product = find(id: row_to_hash[:id])
        update_product.attributes = row.to_hash.slice!(csv_attributes)
        update_products << update_product
      else
        new_product = new
        new_product.attributes = row.to_hash.slice!(csv_attributes)
        new_products << new_product
      end
    end
    if update_products.present?
      import update_products, on_duplicate_key_update: csv_attributes
    elsif
      import new_products
    end
  end
  
  #いいね機能
  acts_as_likeable
  
  private
    def self.csv_attributes
      [:name, :description, :price, :recommended_flag, :carriage_flag]
    end
end

app/controllers/dashboard/categories_controller.rb
class Dashboard::CategoriesController < ApplicationController
    before_action :authenticate_admin!, except: :index
    before_action :set_category, only: %w[show edit update destroy]
    layout "dashboard/dashboard"

    def index
      @categories = Category.display_list(params[:page])
      @category = Category.new
      @major_categories = MajorCategory.all
    end
    
    def show
    end

    def create
      category = Category.new(category_params)
      category.save
      redirect_to dashboard_categories_path
    end

    def edit
      @major_categories = MajorCategory.all
    end

    def update
      @category.update(category_params)
      @category.save
      redirect_to dashboard_categories_path
    end

    def destroy
      @category.destroy
      redirect_to dashboard_categories_path
    end

    private
    
      def set_category
        @category = Category.find(params[:id])
      end

      def category_params
        params.require(:category).permit(:name,:description,:major_category_name, :major_category_id)
      end
end

app/controllers/dashboard/major_categories_controller.rb
class Dashboard::MajorCategoriesController < ApplicationController
    before_action :authenticate_admin!
    before_action :set_major_category, only: %w[show edit update destroy]
    layout "dashboard/dashboard"
    
    def index
      @major_categories = MajorCategory.display_list(params[:pages])
      @major_category = MajorCategory.new
    end
    
    def show
    end
    
    def create
      major_category = MajorCategory.new(major_category_params)
      major_category.save
      redirect_to dashboard_major_categories_path
    end
    
    def edit
    end
    
    def update
      @major_category.update(major_category_params)
      redirect_to dashboard_major_categories_path
    end
    
    def destroy
      @major_category.destroy
      redirect_to dashboard_major_categories_path
    end
    
    private
      def set_major_category
        @major_category = MajorCategory.find(params[:id]) 
      end
      
      def major_category_params
        params.require(:major_category).permit(:name, :description)
      end
end

app/controllers/dashboard/orders_controller.rb
class Dashboard::OrdersController < ApplicationController
  before_action :authenticate_admin!
  layout "dashboard/dashboard"
  
  def index
    if params[:code].present?
      @orders = ShoppingCart.search_bought_carts_by_ids(params[:code]).page(params[:page]).per(15)
    else
      @orders = ShoppingCart.bought_carts.page(params[:page]).per(15)
    end
  end
end

app/controllers/dashboard/products_controller.rb
class Dashboard::ProductsController < ApplicationController
    before_action :authenticate_admin!
    before_action :set_product, only: %w[show edit update destroy]
    layout "dashboard/dashboard"
    
    def index
        @sorted = ""
        @sort_list = Product.sort_list
        
        if params[:sort].present?
          @sorted = params[:sort]
        end
        
        if params[:keyword].present?
          keyword = params[:keyword].strip
          @total_count = Product.search_for_id_and_name(keyword).count
          @products = Product.search_for_id_and_name(keyword).display_list(params[:pages])
        else      
          @total_count = Product.count
          @products = Product.sort_order(@sorted).display_list(params[:page])
        end
    end
        
    def new
        @product = Product.new
        @categories = Category.all
    end

    def create
        @product = Product.new(product_params)
        @product.save
        redirect_to dashboard_products_path
    end

    def edit
        @categories = Category.all
    end

    def update
        @product.update(product_params)
        redirect_to dashboard_products_path
    end

    def destroy
        @product.destroy
        redirect_to dashboard_products_path
    end
    
    def import
    end
    
    def import_csv
        if params[:file] && File.extname(params[:file].original_filename) == ".csv"
            Product.import_csv(params[:file])
            flash[:success] = "CSVでの一括登録が成功しました!"
            redirect_to import_csv_dashboard_products_url
        else
            flash[:danger] = "CSVが追加されていません。CSVを追加してください。"
            redirect_to import_csv_dashboard_products_url
        end
    end
    
    def download_csv
        send_file(
            "#{Rails.root}/public/csv/products.csv",
            filename: "products.csv",
            type: :csv
        )
    end

    private
    def set_product
        @product = Product.find(params[:id])
    end

    def product_params
        params.require(:product).permit(:name, :description, :price, :recommended_flag, :carriage_flag, :category_id, :image)
    end
end

app/controllers/dashboard/users_controller.rb
class Dashboard::UsersController < ApplicationController
    before_action :authenticate_admin!
    layout "dashboard/dashboard"
    
    def index
      if params[:keyword].present?
        @keyword = params[:keyword].strip
        @users = User.search_information(@keyword).display_list(params[:pages])
      else
        @keyword = ""
        @users = User.display_list(params[:pages])
      end
    end
    
    def destroy
      user = User.find(params[:id])
      deleted_flg = User.switch_flg(user.deleted_flg)
      user.update(deleted_flg: deleted_flg)
      redirect_to dashboard_users_path
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
    before_action :authenticate_admin!
    layout 'dashboard/dashboard'
    
    def index
      @sort = params[:sort]
      @sort_list = ShoppingCart.sort_list
      
      if @sort == "month"
        sales = ShoppingCart.get_monthly_sales
      else
        sales = ShoppingCart.get_daily_sales
      end
      
      @sales = Kaminari.paginate_array(sales).page(params[:page]).per(15)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy, :favorite]
  PER = 15
  
  def index
    if sort_params.present?
      @products = Product.sort_products(sort_params, params[:page])
      @category = Category.request_category(sort_params[:sort_category])
    elsif params[:category].present?
      @category = Category.request_category(params[:category])
      @products = Product.category_products(@category, params[:page])
    else
      @products = Product.display_list(params[:page])
    end
    
    @categories = Category.all
    @major_category_names = Category.major_categories
    @sort_list = Product.sort_list
  end

  def show
    @reviews = @product.reviews_with_id
    @review = @reviews.new
    @star_repeat_select = Review.star_repeat_select
  end

  def destroy
    @product.destroy
    redirect_to products_url
  end
  
  def favorite
    current_user.toggle_like!(@product)
    redirect_to product_url @product
  end
  
  private
  
  def product_params
    params.require(:product).permit(:name, :description, :price, :category_id)
  end
  
  def set_product
    @product = Product.find(params[:id])
  end
  
  def sort_params
    params.permit(:sort, :sort_category)
  end
end

app/helpers/dashboard/categories_helper.rb
module Dashboard::CategoriesHelper
end

app/helpers/dashboard/major_categories_helper.rb
module Dashboard::MajorCategoriesHelper
end

app/helpers/dashboard/orders_helper.rb
module Dashboard::OrdersHelper
end

app/helpers/dashboard/products_helper.rb
module Dashboard::ProductsHelper
end

app/helpers/dashboard/users_helper.rb
module Dashboard::UsersHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/dashboard/products/edit.html.erb
<div class="w-50">
  <h1>商品編集</h1>

  <%= form_with model: @product, url: dashboard_product_path, local: true do |f| %>
    <div class="form-inline mt-4 mb-4 row">
      <%= f.label :name, "商品名", class: "col-2 d-flex justify-content-start" %>
      <%= f.text_field :name, class: "form-control col-8" %>
    </div>
    
    <div class="form-inline mt-4 mb-4 row">
      <%= f.label :description, "商品説明", class: "col-2 d-flex justify-content-start" %>
      <%= f.text_area :description, class: "form-control col-8" %>
    </div>    

    <div class="form-inline mt-4 mb-4 row">
      <%= f.label :price, "価格", class: "col-2 d-flex justify-content-start" %>
      <%= f.text_field :price, class: "form-control col-8" %>
    </div>

    <div class="form-inline mt-4 mb-4 row">
      <%= f.label :category_id, "カテゴリ", class: "col-2 d-flex justify-content-start" %>
      <%= f.select :category_id, Category.all.map { |category| [category.name, category.id] }, {}, class: "form-control" %>
    </div>
    
    <div class="form-inline mt-4 mb-4 row">
      <%= f.label :recommended_flag, "オススメ?", class: "col-2 d-flex justify-content-start" %>
      <%= f.check_box :recommended_flag, class: "samazon-check-box" %>
    </div>
    
    <div class="form-inline mt-4 mb-4 row">
      <%= f.label :carriage_flag, "送料", class: "col-2 d-flex justify-content-start" %>
      <%= f.check_box :carriage_flag, class: "samazon-check-box" %>
    </div>
    
    <div class="form-inline mt-4 mb-4 row">
      <%= f.label "画像", class: "col-2 d-flex justify-content-start" %>
      <% if @product.image.attached? %>
        <%= image_tag @product.image, id: "product-image-preview", class: "img-fluid w-25" %>
      <% else %>
        <img src="#" id="product-image-preview" class="">
      <% end %>
      <div class="d-flex flex-column ml-2">
        <small class="mb-3">600px×600px推奨。<br>商品の魅力が伝わる画像をアップロードして下さい。</small>
        <%= f.label "画像を選択", for: "product_image", class: "btn samazon-submit-button" %>
        <%= f.file_field :image, { onChange: "javascript: handleImage(this.files);", style: "display: none;"} %>
      </div>
    </div>

    <%= f.submit "更新", class: "w-25 btn samazon-submit-button" %>
  <% end %>

  <div class="mt-4"><%= link_to "商品一覧に戻る", dashboard_products_path %></div>
</div>

<%= javascript_include_tag "dashboard/products/edit" %>

app/views/dashboard/products/import.html.erb
<% if flash[:success] %><p class="alert alert-success w-75"><%= flash[:success] %></p><% end %>
<% if flash[:danger] %><p class="alert alert-danger w-75"><%= flash[:danger] %></p><% end %>

<div class="w-75">
  <h1>商品CSV登録</h1>
  <%= form_with model: @product, url: import_csv_dashboard_products_path, local: true do |f| %>
    <div class="d-flex flex-column">
      <div class="d-flex flex-row">
        <%= f.label "CSVファイルを選択", for: "file" ,class: "btn samazon-button mr-3 mb-0" %>
        <%= f.file_field :file, onChange: "handleCSV(this.files)",style: "display: none;" %>
        <%= f.submit "一括登録", class: "btn samazon-submit-button" %>
      </div>
    </div>
    <small id="product-import-csv-filename"></small>
  <% end %>

  <div class="d-flex justify-content-between mt-3">
    <h4 class="d-flex align-self-center mt-1 mb-0">CSVファイルフォーマット</h4>
    <%= link_to "雛形ファイルダウンロード", import_csv_download_dashboard_products_path, class: "btn samazon-button" %>
  </div>

  <hr>

  <div class="row">
    <label class="col-3">商品ID</label>
    <span class="col-9">新規登録の場合は空にしてください。既存の商品を更新する場合は、商品IDを指定してください。</span>

    <label class="col-3">商品名</label>
    <span class="col-9"></span>

    <label class="col-3">商品説明</label>
    <span class="col-9"></span>

    <label class="col-3">価格</label>
    <span class="col-9"></span>

    <label class="col-3">カテゴリID</label>
    <span class="col-9"></span>

    <label class="col-3">オススメ商品フラグ</label>
    <span class="col-9"></span>

    <label class="col-3">送料フラグ</label>
    <span class="col-9"></span>
  </div>

  <hr>
</div>

<%= javascript_include_tag "dashboard/products/import" %>

app/views/dashboard/products/index.html.erb
<h1>商品管理</h1>
<%= form_with url: dashboard_products_path, method: :get, local: true, class: "form-inline" do |f| %>
    並び替え
  <% if @sorted.present? %>
    <%= f.select :sort, @sort_list, { selected: @sorted }, { onChange: "javascript: this.form.submit();", class: "form-inline ml-2 form-control" } %>
  <% else %>
    <%= f.select :sort, @sort_list, {}, { onChange: "javascript: this.form.submit();", class: "form-inline ml-2 form-control" } %>
  <% end %>
<% end %>
<div class="w-75 mt-2">
  <div class="w-75">
    <%= form_with url: dashboard_products_path, method: :get, local: true do |f| %>
      <div class="d-flex flex-inline form-group">
        <div class="d-flex align-items-center">
          商品ID・商品名
        </div>
        <%= f.text_area :keyword, class: "form-control ml-2 w-50" %>
      </div>
      <%= f.submit "検索", class: "btn samazon-submit-button" %>
    <% end %>
  </div>

  <div class="d-flex justify-content-between w-75 mt-4">
    <h3>合計<%= @total_count %>件</h3>

    <%= link_to "+ 新規作成", new_dashboard_product_path, class: "btn samazon-submit-button" %>
  </div>
  <table class="table table-responsive mt-5">

    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">画像</th>
        <th scope="col">商品名</th>
        <th scope="col">価格</th>
        <th scope="col">カテゴリ名</th>
        <th scope="col">親カテゴリ名</th>
        <th scope="col"></th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% @products.each do |product| %>
      <tr>
        <th scope="row"><%= product.id %></td>
        <td>
          <% if product.image.attached? %>
            <%= image_tag product.image, class: "h-10 img-fluid" %>
          <% else %>
            <%= image_tag "/images/dummy.png", class: "h-10 img-fluid" %>
          <% end %>
        </td>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td><%= product.category.name %></td>
        <td><%= product.category.major_category_name %></td>
        <td>
          <%= link_to "編集", edit_dashboard_product_path(product), class: "dashboard-edit-link" %>
        </td>
        <td>
          <%= link_to "削除", dashboard_product_path(product), method: :delete, class: "dashboard-delete-link" %>
        </td>                  
      </tr>
      <% end %>
    </tbody>
  </table>

  <%= paginate @products %>
</div>

app/views/dashboard/products/new.html.erb
<div class="w-50">
  <h1>商品登録</h1>

  <hr>

  <%= form_with model: @product, url: dashboard_products_path, local: true do |f| %>
    <div class="form-inline mt-4 mb-4 row">
      <%= f.label "商品名", class: "col-2 d-flex justify-content-start" %>
      <%= f.text_field :name, class: "form-control col-8" %>
    </div>

    <div class="form-inline mt-4 mb-4 row">
      <%= f.label "商品説明", class: "col-2 d-flex justify-content-start" %>
      <%= f.text_area :description, class: "form-control col-8" %>
    </div>

    <div class="form-inline mt-4 mb-4 row">
      <%= f.label "価格", class: "col-2 d-flex justify-content-start" %>
      <%= f.number_field :price, class: "form-control col-8" %>
    </div>

    <div class="form-inline mt-4 mb-4 row">
      <%= f.label "カテゴリ", class: "col-2 d-flex justify-content-start" %>
      <%= f.collection_select(:category_id, @categories, :id, :name) %>
    </div>
    
    <div class="form-inline mt-4 mb-4 row">
      <%= f.label "オススメ?", class: "col-2 d-flex justify-content-start" %>
      <%= f.check_box :recommended_flag, class: "samazon-check-box" %>
    </div>
    
    <div class="form-inline mt-4 mb-4 row">
      <%= f.label "送料", class: "col-2 d-flex justify-content-start" %>
      <%= f.check_box :carriage_flag, class: "samazon-check-box" %>
    </div>
    
    <div class="form-inline mt-4 mb-4 row">
      <%= f.label "画像", class: "col-2 d-flex justify-content-start" %>
      <% if @product.image.attached? %>
        <%= image_tag @product.image, id: "product-image-preview", class: "img-fluid w-25" %>
      <% else %>
        <img src="#" id="product-image-preview" class="">
      <% end %>
      <div class="d-flex flex-column ml-2">
        <small class="mb-3">600px×600px推奨。<br>商品の魅力が伝わる画像をアップロードして下さい。</small>
        <%= f.label "画像を選択", for: "product_image", class: "btn samazon-submit-button" %>
        <%= f.file_field :image, { onChange: "javascript: handleImage(this.files);", style: "display: none;"} %>
      </div>
    </div>
    <%= f.submit "商品を登録", class:"btn samazon-submit-button" %>
  <% end %>

  <div class="mt-4"><%= link_to "商品一覧に戻る", dashboard_products_path %></div>
</div>

<%= javascript_include_tag "dashboard/products/new" %>