config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admins, :controllers => {
    :sessions => 'admins/sessions'
  }
  
  devise_scope :admin do
    get "dashboard", :to => 'dashboard#index'
    get "dashboard/login", :to => "admins/sessions#new"
    post "dashboard/login", :to => "admins/sessions#create"
    delete "dashboard/logout", :to => "admins/sessions#destroy"
  end
  
  namespace :dashboard do
    resources :users, only: [:index, :destroy]
    resources :major_categories, except: [:new]
    resources :categories, except: [:new]
    resources :products, except: [:show] do
      collection do
        get  "import/csv", :to => "products#import"
        post "import/csv", :to => "products#import_csv"
        get  "import/csv_download", :to => "products#download_csv"
      end
    end
    resources :orders, only: [:index]
  end
  
  devise_for :users, :controllers => {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions',
    :passwords => 'users/passwords',
    :confirmations => 'users/confirmations',
    :unlocks => 'users/unlocks',
  }
  
  devise_scope :user do
    root :to => "web#index"
    get "signup", :to => "users/registrations#new"
    get "verify", :to => "users/registrations#verify"
    get "login", :to => "users/sessions#new"
    delete "logout", :to => "users/sessions#destroy"
  end
  
  resource :users, only: [:edit, :update] do
    collection do
      get "cart", :to => "shopping_carts#index"
      post "cart/create", :to => "shopping_carts#create"
      delete "cart", :to => "shopping_carts#destroy"
      get 'mypage', :to => "users#mypage"
      get 'mypage/edit', :to => "users#edit"
      get 'mypage/address/edit', :to => "users#edit_address" 
      get "mypage", :to => "users#update"
      get "mypage/edit_password", :to => "users#edit_password"
      put "mypage/password", :to => "users#update_password"
      get  "mypage/favorite", :to => "users#favorite"
      delete "mypage/delete", :to => "users#destroy"
      get "mypage/cart_history", :to => "users#cart_history_index", :as => "mypage_cart_histories"
      get "mypage/cart_history/:num", :to => "users#cart_history_show", :as => "mypage_cart_history"
      get    "mypage/register_card",     :to => "users#register_card"
      post   "mypage/token",             :to => "users#token"
    end
  end
  
  resources :products do
    member  do
      get :favorite
    end
    resources :reviews, only: [:create]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :reviews
  has_one_attached :image
  
  def reviews_new
      reviews.new
  end
  
  def reviews_with_id
    reviews.reviews_with_id
  end
  
  
  extend DisplayList
  scope :on_category, -> (category) { where(category_id: category) }
  
  scope :sort_order, -> (order) { order(order) }
  scope :category_products, -> (category, page) { 
    on_category(category).
    display_list(page)
  }
  
  scope :search_for_id_and_name, -> (keyword) {
    where("name LIKE ?", "%#{keyword}%").or(where("id LIKE ?", "%#{keyword}%"))
  }
  
  scope :sort_products, -> (sort_order, page) {
    on_category(sort_order[:sort_category]).
    sort_order(sort_order[:sort]).
    display_list(page)
  }
  
  scope :sort_list, -> {
    {
      "並び替え" => "",
      "価格の安い順" => "price asc",
      "価格の高い順" => "price desc",
      "出品の古い順" => "updated_at asc", 
      "出品の新しい順" => "updated_at desc",
    }
  }
  
  scope :recently_products, -> (number) { order(created_at: "desc").take(number) }
  scope :recommend_products, -> (number) { where(recommended_flag: true).take(number) }
  scope :check_products_carriage_list, -> (product_ids) { where(id: product_ids).pluck(:carriage_flag)}
  
  def self.import_csv(file)
    new_products = []
    update_products = []
    
    CSV.foreach(file.path, headers: true, encoding: "Shift_JIS:UTF-8") do |row|
      row_to_hash = row.to_hash
      byebug
      if row_to_hash[:id].present?
        update_product = find(id: row_to_hash[:id])
        update_product.attributes = row.to_hash.slice!(csv_attributes)
        update_products << update_product
      else
        new_product = new
        new_product.attributes = row.to_hash.slice!(csv_attributes)
        new_products << new_product
      end
    end
    if update_products.present?
      import update_products, on_duplicate_key_update: csv_attributes
    elsif
      import new_products
    end
  end
  
  #いいね機能
  acts_as_likeable
  
  private
    def self.csv_attributes
      [:name, :description, :price, :recommended_flag, :carriage_flag]
    end
end

app/controllers/dashboard/products_controller.rb
class Dashboard::ProductsController < ApplicationController
    before_action :authenticate_admin!
    before_action :set_product, only: %w[show edit update destroy]
    layout "dashboard/dashboard"
    
    def index
        @sorted = ""
        @sort_list = Product.sort_list
        
        if params[:sort].present?
          @sorted = params[:sort]
        end
        
        if params[:keyword].present?
          keyword = params[:keyword].strip
          @total_count = Product.search_for_id_and_name(keyword).count
          @products = Product.search_for_id_and_name(keyword).display_list(params[:pages])
        else      
          @total_count = Product.count
          @products = Product.sort_order(@sorted).display_list(params[:page])
        end
    end
        
    def new
        @product = Product.new
        @categories = Category.all
    end

    def create
        @product = Product.new(product_params)
        @product.save
        redirect_to dashboard_products_path
    end

    def edit
        @categories = Category.all
    end

    def update
        @product.update(product_params)
        redirect_to dashboard_products_path
    end

    def destroy
        @product.destroy
        redirect_to dashboard_products_path
    end
    
    def import
    end
    
    def import_csv
        if params[:file] && File.extname(params[:file].original_filename) == ".csv"
            Product.import_csv(params[:file])
            flash[:success] = "CSVでの一括登録が成功しました!"
            redirect_to import_csv_dashboard_products_url
        else
            flash[:danger] = "CSVが追加されていません。CSVを追加してください。"
            redirect_to import_csv_dashboard_products_url
        end
    end
    
    def download_csv
        send_file(
            "#{Rails.root}/public/csv/products.csv",
            filename: "products.csv",
            type: :csv
        )
    end

    private
    def set_product
        @product = Product.find(params[:id])
    end

    def product_params
        params.require(:product).permit(:name, :description, :price, :recommended_flag, :carriage_flag, :category_id, :image)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy, :favorite]
  PER = 15
  
  def index
    if sort_params.present?
      @products = Product.sort_products(sort_params, params[:page])
      @category = Category.request_category(sort_params[:sort_category])
    elsif params[:category].present?
      @category = Category.request_category(params[:category])
      @products = Product.category_products(@category, params[:page])
    else
      @products = Product.display_list(params[:page])
    end
    
    @categories = Category.all
    @major_category_names = Category.major_categories
    @sort_list = Product.sort_list
  end

  def show
    @reviews = @product.reviews_with_id
    @review = @reviews.new
    @star_repeat_select = Review.star_repeat_select
  end

  def destroy
    @product.destroy
    redirect_to products_url
  end
  
  def favorite
    current_user.toggle_like!(@product)
    redirect_to product_url @product
  end
  
  private
  
  def product_params
    params.require(:product).permit(:name, :description, :price, :category_id)
  end
  
  def set_product
    @product = Product.find(params[:id])
  end
  
  def sort_params
    params.permit(:sort, :sort_category)
  end
end

app/helpers/dashboard/products_helper.rb
module Dashboard::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/index.html.erb
<div class="row">
  <div class="col-2">
    <%= render partial: "layouts/sidebar", locals: { categories: @categories, major_category_names: @major_category_names } %>
  </div>
  <div class="col-9">
    <div class="container">
      <% if @category.present? %>
        <%= link_to "トップ", "#", category: @major_category_name %> > <%= @category.name %>
        <h1><%= @category.name %>の商品一覧<%= @products.count %>件</h1>
        <%= form_with url: products_path, method: :get, local: true, class: "form-inline" do |f| %>
          <%= f.hidden_field :sort_category, value: @category.id %>
          並び替え
          <% if @sorted.present? %>
            <%= f.select :sort, @sort_list, selected: @sorted, onChange: "javascript: this.form.submit();", class: "form-inline ml-2" %>
          <% else %>
            <%= f.select :sort, @sort_list, {}, onChange: "javascript: this.form.submit();", class: "form-inline ml-2" %>
          <% end %>
        <% end %>
      <% end %>
    </div>
    <div class="container mt-4">
      <div class="row w-100">
        <% @products.each do |product| %>
        <div class="col-3">
          <%= link_to product_path(product) do %>
            <% if product.image.attached? %>
              <%= image_tag product.image, class: "img-thumbnail" %>
            <% else %>
              <%= image_tag "/images/dummy.png", class: "img-thumbnail" %>
            <% end %>
          <% end %>
          <div class="row">
            <div class="col-12">
              <p class="samazon-product-label mt-2">
                <%= product.name %>
                <label><%= product.price %></label>
              </p>
            </div>
          </div>
        </div>
        <% end %>
      </div>
    </div>
    <%= paginate @products %>
  </div>
</div>

app/views/products/show.html.erb
<div class="d-flex justify-content-center">
  <div class="row w-75">
    <div class="col-5 offset-1">
      <% if @product.image.attached? %>
        <%= image_tag @product.image, class: "w-100 img-fuild" %>
      <% else %>
        <%= image_tag "/images/dummy.png", class: "w-100 img-fuild" %>
      <% end %>
    </div>

    <div class="col">
      <div class="d-flex flex-column">
        <h1 class="">
          <%= @product.name %>
        </h1>
        <p class="">
          <%= @product.description %>
        </p>
        <hr>
        <p class="d-flex align-items-end">
          ￥<%= @product.price %>（税込）
        </p>
        <hr>
      </div>

      <% if user_signed_in? %>
        <%= form_with url: cart_create_users_path, local: true do |f| %>
          <%= f.hidden_field :product_id, value: @product.id %>
          <%= f.hidden_field :name, value: @product.name %>
          <%= f.hidden_field :price, value: @product.price %>
          <div class="form-group row">
            <%= f.label "数量", class: "col-sm-2 col-form-label" %>
            <div class="col-sm-10">
              <%= f.number_field :quantity, min:1, value:1, class: "form-control w-25"%>
            </div>
          </div>
          <div class="row">
            <div class="col-7">
              <%= f.submit "カートに追加", class: "btn samazon-submit-button w-100" do %>
                <i class="fas fa-shopping-cart"></i>
              <% end %>
            </div>
            <div class="col-5">
              <%= link_to favorite_product_path, class: "btn samazon-favorite-button text-favorite w-100" do %>
                <i class="fa fa-heart"></i><%= current_user.likes?(@product) ? "お気に入り解除" : "お気に入り" %>
              <% end %>
            </div>
          </div>
        <% end %>
      <% end %>

    </div>

    <div class="offset-1 col-11">
      <hr class="w-100">
      <h3 class="float-left">カスタマーレビュー</h3>
    </div>

    <div class="offset-1 col-10">
      <!-- レビューを実装する箇所になります -->
      <div class="row">
        <% @reviews.each do |review| %>
          <div class="offset-md-5 col-md-5">
            <h3 class="review-score-color"><%= score_on_star(review.score) %></h3>
            <p class="h3"><%= review.content %></p>
            <h4><%= review.user.name %></h4>
            <label><%= l review.created_at %></label>
          </div>
        <% end %>
      </div>
      
      <% if user_signed_in? %>
        <div class="row">
          <div class="offset-md-5 col-md-5">
            <%= form_with model: @review, url: product_reviews_path(@product) do |f| %>
            　<h4>評価</h4>
            　<%= f.select :score, @star_repeat_select, {}, class: "form-control m-2 review-score-color" %>
            　<h4>レビュー内容</h4>
              <%= f.text_area :content, class: "form-control m-2" %>
              <%= f.submit "レビューを追加" , class:"btn samazon-submit-button ml-2"%>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>